# Generated by Django 5.2.4 on 2026-03-31 13:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('url', models.URLField()),
                ('ativa', models.BooleanField(default=True)),
                ('tipo_coleta', models.CharField(choices=[('rss', 'RSS'), ('html', 'HTML'), ('api', 'API')], default='html', max_length=20)),
                ('categoria_padrao', models.CharField(blank=True, max_length=80)),
                ('parser_key', models.CharField(blank=True, max_length=80)),
                ('headers_json', models.JSONField(blank=True, default=dict)),
                ('confianca_minima', models.DecimalField(decimal_places=2, default=0.7, max_digits=4)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='JobExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(default='sync_home_news', max_length=120)),
                ('status', models.CharField(choices=[('running', 'Executando'), ('success', 'Sucesso'), ('partial', 'Parcial'), ('failed', 'Falhou')], default='running', max_length=20)),
                ('horario', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('quantidade_processada', models.PositiveIntegerField(default=0)),
                ('quantidade_publicada', models.PositiveIntegerField(default=0)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-horario'],
            },
        ),
        migrations.CreateModel(
            name='MateriaBruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_original', models.URLField(unique=True)),
                ('titulo_extraido', models.CharField(blank=True, max_length=300)),
                ('html_bruto', models.TextField(blank=True)),
                ('texto_base', models.TextField(blank=True)),
                ('hash_conteudo', models.CharField(db_index=True, max_length=64)),
                ('imagem_url', models.URLField(blank=True)),
                ('data_publicacao_original', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('processada_em', models.DateTimeField(blank=True, null=True)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_brutas', to='portal.fonte')),
            ],
            options={
                'ordering': ['-data_coleta'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaPublicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('resumo', models.TextField()),
                ('conteudo', models.TextField()),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='portal/noticias/')),
                ('imagem_url', models.URLField(blank=True)),
                ('imagem_ilustrativa', models.BooleanField(default=False)),
                ('url_fonte', models.URLField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('archived', 'Arquivada')], default='draft', max_length=20)),
                ('confianca', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('publicada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('fonte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='portal.fonte')),
                ('materia_bruta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticia_publicada', to='portal.materiabruta')),
            ],
            options={
                'ordering': ['-publicada_em', '-criada_em'],
                'indexes': [models.Index(fields=['status', '-publicada_em'], name='portal_noti_status_ccb063_idx'), models.Index(fields=['slug'], name='portal_noti_slug_aff72b_idx')],
            },
        ),
    ]
