# Generated by Django 5.2.4 on 2026-04-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_noticiapublicada_topico_tags_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalMetricDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(db_index=True)),
                ('metric_type', models.CharField(choices=[('page_view', 'Page View'), ('click', 'Click')], db_index=True, max_length=20)),
                ('path', models.CharField(blank=True, db_index=True, max_length=255)),
                ('event_name', models.CharField(blank=True, db_index=True, max_length=80)),
                ('section', models.CharField(blank=True, max_length=80)),
                ('article_slug', models.CharField(blank=True, db_index=True, max_length=240)),
                ('article_category', models.CharField(blank=True, max_length=120)),
                ('article_topic', models.CharField(blank=True, max_length=120)),
                ('total', models.PositiveIntegerField(default=0)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-metric_date', '-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='noticiapublicada',
            new_name='portal_noti_status_ec9cca_idx',
            old_name='portal_noti_status_81dad4_idx',
        ),
        migrations.AddConstraint(
            model_name='portalmetricdaily',
            constraint=models.UniqueConstraint(fields=('metric_date', 'metric_type', 'path', 'event_name', 'section', 'article_slug', 'article_category', 'article_topic'), name='portal_metric_daily_unique_bucket'),
        ),
    ]
