# Generated by Django 5.2.4 on 2026-04-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_metricas_e_leads_por_ambiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAlertaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=40)),
                ('origem_cadastro', models.CharField(choices=[('home', 'Home'), ('alertas', 'Página de alertas')], default='alertas', max_length=20)),
                ('aceite_versao', models.CharField(blank=True, max_length=40)),
                ('aceito_em', models.DateTimeField(blank=True, null=True)),
                ('aceito_ip', models.CharField(blank=True, max_length=45)),
                ('aceito_user_agent', models.CharField(blank=True, max_length=255)),
                ('source_environment', models.CharField(db_index=True, default='local', max_length=20)),
                ('source_host', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('descadastrado', 'Descadastrado')], default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead de alertas por e-mail',
                'verbose_name_plural': 'Leads de alertas por e-mail',
                'ordering': ['-criado_em'],
            },
        ),
    ]
