# Generated by Django 5.2.4 on 2026-04-16 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_artigos_educativos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone (ex: book, star, plane)', max_length=50)),
                ('cor', models.CharField(default='#2563eb', help_text='Cor hex do módulo', max_length=7)),
                ('ordem', models.PositiveIntegerField(db_index=True, default=0)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Módulo de estudo',
                'verbose_name_plural': 'Módulos de estudo',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ArtigoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('resumo', models.TextField(help_text='Resumo curto para exibição em cards')),
                ('conteudo', models.TextField(help_text='Conteúdo HTML completo do artigo')),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='portal/artigos/')),
                ('imagem_url', models.URLField(blank=True)),
                ('autor', models.CharField(default='Redação NC Fly', max_length=120)),
                ('tempo_leitura', models.PositiveIntegerField(default=5, help_text='Tempo de leitura em minutos')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], db_index=True, default='draft', max_length=20)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('keywords_json', models.JSONField(blank=True, default=list)),
                ('youtube_search_terms_json', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('ia_revisao_json', models.JSONField(blank=True, default=dict)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='portal.moduloestudo')),
            ],
            options={
                'verbose_name': 'Artigo de estudo',
                'verbose_name_plural': 'Artigos de estudo',
                'ordering': ['modulo__ordem', 'ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ArtigoVideoYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('canal', models.CharField(blank=True, max_length=200)),
                ('duracao', models.CharField(blank=True, help_text='Ex: 12:34', max_length=20)),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('termo_busca', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('buscado_em', models.DateTimeField(auto_now_add=True)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='portal.artigoestudo')),
            ],
            options={
                'verbose_name': 'Vídeo do YouTube (artigo)',
                'verbose_name_plural': 'Vídeos do YouTube (artigos)',
                'ordering': ['ordem', '-visualizacoes'],
                'constraints': [models.UniqueConstraint(fields=('artigo', 'video_id'), name='unique_artigo_video')],
            },
        ),
        migrations.AddIndex(
            model_name='artigoestudo',
            index=models.Index(fields=['status', '-publicado_em'], name='portal_arti_status_7233f2_idx'),
        ),
        migrations.AddIndex(
            model_name='artigoestudo',
            index=models.Index(fields=['slug'], name='portal_arti_slug_7984b4_idx'),
        ),
        migrations.AddIndex(
            model_name='artigoestudo',
            index=models.Index(fields=['modulo', 'ordem'], name='portal_arti_modulo__ca707a_idx'),
        ),
    ]
