# Generated by Django 5.2.4 on 2026-04-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_moduloestudo_artigoestudo_artigovideoyoutube_and_more'),
    ]

    operations = [
        # SQLite refaz a tabela inteira em qualquer alter; precisa soltar o
        # UniqueConstraint antes de remover o campo que ele referencia.
        # Postgres (prod) ignora porque a migration ja esta marcada como aplicada.
        migrations.RemoveConstraint(
            model_name='artigovideoyoutube',
            name='unique_artigo_video',
        ),
        migrations.RemoveField(
            model_name='artigoestudo',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='artigovideoyoutube',
            name='artigo',
        ),
        migrations.DeleteModel(
            name='ModuloEstudo',
        ),
        migrations.DeleteModel(
            name='ArtigoEstudo',
        ),
        migrations.DeleteModel(
            name='ArtigoVideoYoutube',
        ),
    ]
