# Generated by Django 5.2.4 on 2026-04-17 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_remove_artigoestudo_modulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('resumo', models.TextField(blank=True)),
                ('conteudo', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='artigos/')),
                ('imagem_url', models.URLField(blank=True)),
                ('autor', models.CharField(blank=True, max_length=150)),
                ('tempo_leitura', models.PositiveIntegerField(default=5)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=20)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('keywords_json', models.JSONField(blank=True, default=list)),
                ('youtube_search_terms_json', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('ia_revisao_json', models.JSONField(blank=True, default=dict)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artigo de estudo',
                'verbose_name_plural': 'Artigos de estudo',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ModuloEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(blank=True, max_length=60)),
                ('cor', models.CharField(blank=True, max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modulo de estudo',
                'verbose_name_plural': 'Modulos de estudo',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ArtigoVideoYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('canal', models.CharField(blank=True, max_length=150)),
                ('duracao', models.CharField(blank=True, max_length=20)),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('termo_busca', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('buscado_em', models.DateTimeField(blank=True, null=True)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='portal.artigoestudo')),
            ],
            options={
                'verbose_name': 'Video do YouTube',
                'verbose_name_plural': 'Videos do YouTube',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='artigoestudo',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='portal.moduloestudo'),
        ),
    ]
