# Generated by Django 5.2.4 on 2026-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_artigoestudo_moduloestudo_artigovideoyoutube_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigoestudo',
            options={'ordering': ['modulo__ordem', 'ordem', 'titulo'], 'verbose_name': 'Artigo de estudo', 'verbose_name_plural': 'Artigos de estudo'},
        ),
        migrations.AlterModelOptions(
            name='artigovideoyoutube',
            options={'ordering': ['ordem', '-visualizacoes'], 'verbose_name': 'Vídeo do YouTube (artigo)', 'verbose_name_plural': 'Vídeos do YouTube (artigos)'},
        ),
        migrations.AlterModelOptions(
            name='moduloestudo',
            options={'ordering': ['ordem', 'titulo'], 'verbose_name': 'Módulo de estudo', 'verbose_name_plural': 'Módulos de estudo'},
        ),
        migrations.AlterField(
            model_name='artigoestudo',
            name='autor',
            field=models.CharField(default='Redação NC Fly', max_length=120),
        ),
        migrations.AlterField(
            model_name='artigoestudo',
            name='conteudo',
            field=models.TextField(help_text='Conteúdo HTML completo do artigo'),
        ),
        migrations.AlterField(
            model_name='artigoestudo',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='portal/artigos/'),
        ),
        migrations.AlterField(
            model_name='artigoestudo',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='artigoestudo',
            name='resumo',
            field=models.TextField(help_text='Resumo curto para exibição em cards'),
        ),
        migrations.AlterField(
            model_name='artigoestudo',
            name='seo_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='artigoestudo',
            name='slug',
            field=models.SlugField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='artigoestudo',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='artigoestudo',
            name='tempo_leitura',
            field=models.PositiveIntegerField(default=5, help_text='Tempo de leitura em minutos'),
        ),
        migrations.AlterField(
            model_name='artigoestudo',
            name='titulo',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='artigovideoyoutube',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='artigovideoyoutube',
            name='buscado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigovideoyoutube',
            name='canal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='artigovideoyoutube',
            name='duracao',
            field=models.CharField(blank=True, help_text='Ex: 12:34', max_length=20),
        ),
        migrations.AlterField(
            model_name='artigovideoyoutube',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='moduloestudo',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='moduloestudo',
            name='cor',
            field=models.CharField(default='#2563eb', help_text='Cor hex do módulo', max_length=7),
        ),
        migrations.AlterField(
            model_name='moduloestudo',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moduloestudo',
            name='icone',
            field=models.CharField(blank=True, help_text='Nome do ícone (ex: book, star, plane)', max_length=50),
        ),
        migrations.AlterField(
            model_name='moduloestudo',
            name='ordem',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='moduloestudo',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AddIndex(
            model_name='artigoestudo',
            index=models.Index(fields=['status', '-publicado_em'], name='portal_arti_status_7233f2_idx'),
        ),
        migrations.AddIndex(
            model_name='artigoestudo',
            index=models.Index(fields=['slug'], name='portal_arti_slug_7984b4_idx'),
        ),
        migrations.AddIndex(
            model_name='artigoestudo',
            index=models.Index(fields=['modulo', 'ordem'], name='portal_arti_modulo__ca707a_idx'),
        ),
        migrations.AddConstraint(
            model_name='artigovideoyoutube',
            constraint=models.UniqueConstraint(fields=('artigo', 'video_id'), name='unique_artigo_video'),
        ),
    ]
