# Generated by Django 5.2.4 on 2026-04-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_progresso_artigo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='progressoartigo',
            new_name='portal_prog_user_id_2d139c_idx',
            old_name='portal_prog_user_id_artigo_idx',
        ),
        migrations.RenameIndex(
            model_name='progressoartigo',
            new_name='portal_prog_user_id_f48a63_idx',
            old_name='portal_prog_user_lido_idx',
        ),
    ]
