# Generated by Django 5.2.4 on 2026-04-20 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_artigoestudo_notificado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioArtigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_email_snapshot', models.EmailField(max_length=254)),
                ('autor_nome_snapshot', models.CharField(blank=True, max_length=180)),
                ('exibir_nome_completo', models.BooleanField(default=False, help_text='False = email mascarado (ped***@gmail.com). True = nome. Default False por privacidade.')),
                ('corpo', models.TextField(max_length=2000)),
                ('corpo_hash', models.CharField(help_text='SHA-256 do corpo publicado — prova de imutabilidade.', max_length=64)),
                ('status', models.CharField(choices=[('publicado', 'Publicado'), ('oculto_admin', 'Oculto pelo admin'), ('excluido_autor', 'Excluido pelo autor')], db_index=True, default='publicado', max_length=20)),
                ('ocultado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_ocultacao', models.CharField(blank=True, default='', help_text='Motivo do admin ao ocultar — defesa juridica.', max_length=200)),
                ('editado', models.BooleanField(default=False)),
                ('editado_em', models.DateTimeField(blank=True, null=True)),
                ('historico_edicoes', models.JSONField(blank=True, default=list, help_text='Lista de versoes anteriores: [{corpo, corpo_hash, editado_em_iso}, ...]. Defesa legal.')),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ip_cadastro', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='portal.artigoestudo')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='portal.portaluser')),
                ('ocultado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_ocultados', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='portal.comentarioartigo')),
            ],
            options={
                'verbose_name': 'Comentario de artigo',
                'verbose_name_plural': 'Comentarios de artigos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['artigo', 'status', '-criado_em'], name='portal_come_artigo__c79a8c_idx'), models.Index(fields=['parent', '-criado_em'], name='portal_come_parent__7448d2_idx'), models.Index(fields=['autor_email_snapshot', '-criado_em'], name='portal_come_autor_e_7491ac_idx')],
            },
        ),
    ]
