from django.urls import path
from gestao.views import (
    admin_dashboard,
    admin_clientes,
    admin_contas,
    admin_cotacoes,
    deletar_cotacao,
    admin_emissoes,
    nova_emissao,
    editar_emissao,
    deletar_emissao,
    admin_hoteis,
    nova_emissao_hotel,
    editar_emissao_hotel,
    admin_cotacoes_voo,
    nova_cotacao_voo,
    editar_cotacao_voo,
    deletar_cotacao_voo,
    criar_conta,
    editar_conta,
    admin_programas,
    editar_programa,
    deletar_programa,
    criar_programa,
    criar_cliente,
    editar_cliente,
    admin_aeroportos,
    criar_aeroporto,
    editar_aeroporto,
    deletar_aeroporto,
    programas_do_cliente,
    visualizar_cliente,
    admin_movimentacoes,
    admin_nova_movimentacao,
    cotacao_voo_pdf,
    emissao_pdf,
    admin_companhias,
    criar_companhia,
    editar_companhia,
    deletar_companhia,
    admin_auditoria,
    calculadora_cotacao,
)

urlpatterns = [
    path('painel/', admin_dashboard, name='admin_dashboard'),
    path('clientes/', admin_clientes, name='admin_clientes'),
    path('clientes/<int:cliente_id>/editar/', editar_cliente, name='admin_editar_cliente'),
    path('clientes/novo/', criar_cliente, name='admin_novo_cliente'),
    path('clientes/<int:cliente_id>/programas/', programas_do_cliente, name='admin_programas_do_cliente'),
    path('clientes/<int:cliente_id>/painel/', visualizar_cliente, name='admin_visualizar_cliente'),
    path('contas/', admin_contas, name='admin_contas'),
    path('contas/novo/', criar_conta, name='admin_nova_conta'),
    path('contas/<int:conta_id>/editar/', editar_conta, name='admin_editar_conta'),
    path('contas/<int:conta_id>/movimentacoes/', admin_movimentacoes, name='admin_movimentacoes'),
    path('contas/<int:conta_id>/movimentacoes/nova/', admin_nova_movimentacao, name='admin_nova_movimentacao'),
    path('programas/', admin_programas, name='admin_programas'),
    path('programas/novo/', criar_programa, name='admin_novo_programa'),
    path('programas/<int:programa_id>/editar/', editar_programa, name='admin_editar_programa'),
    path('programas/<int:programa_id>/deletar/', deletar_programa, name='admin_deletar_programa'),
    path('aeroportos/', admin_aeroportos, name='admin_aeroportos'),
    path('aeroportos/novo/', criar_aeroporto, name='admin_novo_aeroporto'),
    path('aeroportos/<int:aeroporto_id>/editar/', editar_aeroporto, name='admin_editar_aeroporto'),
    path('aeroportos/<int:aeroporto_id>/deletar/', deletar_aeroporto, name='admin_deletar_aeroporto'),
    path('companhias/', admin_companhias, name='admin_companhias'),
    path('companhias/nova/', criar_companhia, name='admin_nova_companhia'),
    path('companhias/<int:companhia_id>/editar/', editar_companhia, name='admin_editar_companhia'),
    path('companhias/<int:companhia_id>/deletar/', deletar_companhia, name='admin_deletar_companhia'),
    path('cotacoes/', admin_cotacoes, name='admin_cotacoes'),
    path('cotacoes/<int:cotacao_id>/deletar/', deletar_cotacao, name='admin_deletar_cotacao'),
    path('cotacoes-voo/', admin_cotacoes_voo, name='admin_cotacoes_voo'),
    path('cotacoes-voo/calculadora/', calculadora_cotacao, name='admin_calculadora_cotacao'),
    path('cotacoes-voo/nova/', nova_cotacao_voo, name='admin_nova_cotacao_voo'),
    path('cotacoes-voo/<int:cotacao_id>/editar/', editar_cotacao_voo, name='admin_editar_cotacao_voo'),
    path('cotacoes-voo/<int:cotacao_id>/deletar/', deletar_cotacao_voo, name='admin_deletar_cotacao_voo'),
    path('cotacoes-voo/<int:cotacao_id>/pdf/', cotacao_voo_pdf, name='admin_cotacao_voo_pdf'),
    path('emissoes/', admin_emissoes, name='admin_emissoes'),
    path('emissoes/nova/', nova_emissao, name='admin_nova_emissao'),
    path('emissoes/<int:emissao_id>/editar/', editar_emissao, name='admin_editar_emissao'),
    path('emissoes/<int:emissao_id>/deletar/', deletar_emissao, name='admin_deletar_emissao'),
    path('emissoes/<int:emissao_id>/pdf/', emissao_pdf, name='admin_emissao_pdf'),
    path('hoteis/', admin_hoteis, name='admin_hoteis'),
    path('hoteis/nova/', nova_emissao_hotel, name='admin_nova_emissao_hotel'),
    path('hoteis/<int:emissao_id>/editar/', editar_emissao_hotel, name='admin_editar_emissao_hotel'),
    path('auditoria/', admin_auditoria, name='admin_auditoria'),
]
