from django.urls import path
from gestao import views_admin
from .views_admin import (
    admin_dashboard,
    admin_clientes,
    admin_contas,
    admin_cotacoes,
    admin_emissoes,
    nova_emissao,
    editar_emissao,
    admin_hoteis,
    nova_emissao_hotel,
    editar_emissao_hotel,
    admin_cotacoes_voo,
    nova_cotacao_voo,
    editar_cotacao_voo,
    criar_conta,
    editar_conta,
    admin_programas,
    editar_programa,
    criar_cliente,
    editar_cliente,
    admin_aeroportos,
    editar_aeroporto,
)


urlpatterns = [
    path('painel/', admin_dashboard, name='admin_dashboard'),
    path('clientes/', admin_clientes, name='admin_clientes'),
    path('clientes/<int:cliente_id>/editar/', editar_cliente, name='admin_editar_cliente'),
    path('contas/', admin_contas, name='admin_contas'),
    path('contas/<int:conta_id>/editar/', editar_conta, name='admin_editar_conta'),
    path('programas/', admin_programas, name='admin_programas'),
    path('programas/<int:programa_id>/editar/', editar_programa, name='admin_editar_programa'),
    path('aeroportos/', admin_aeroportos, name='admin_aeroportos'),
    path('aeroportos/<int:aeroporto_id>/editar/', editar_aeroporto, name='admin_editar_aeroporto'),
    path('cotacoes/', admin_cotacoes, name='admin_cotacoes'),
    path('cotacoes-voo/', admin_cotacoes_voo, name='admin_cotacoes_voo'),
    path('cotacoes-voo/nova/', nova_cotacao_voo, name='admin_nova_cotacao_voo'),
    path('cotacoes-voo/<int:cotacao_id>/editar/', editar_cotacao_voo, name='admin_editar_cotacao_voo'),
    path('emissoes/', admin_emissoes, name='admin_emissoes'),
    path('emissoes/nova/', nova_emissao, name='admin_nova_emissao'),
    path('emissoes/<int:emissao_id>/editar/', editar_emissao, name='admin_editar_emissao'),
    path('hoteis/', admin_hoteis, name='admin_hoteis'),
    path('hoteis/nova/', nova_emissao_hotel, name='admin_nova_emissao_hotel'),
    path('hoteis/<int:emissao_id>/editar/', editar_emissao_hotel, name='admin_editar_emissao_hotel'),
    path('contas/novo/', criar_conta, name='admin_nova_conta'),
    path('clientes/novo/', criar_cliente, name='admin_novo_cliente'),
    path('clientes/<int:cliente_id>/programas/', views_admin.programas_do_cliente, name='admin_programas_do_cliente'),
    path('clientes/<int:cliente_id>/painel/', views_admin.visualizar_cliente, name='admin_visualizar_cliente'),
    path('contas/<int:conta_id>/movimentacoes/', views_admin.admin_movimentacoes, name='admin_movimentacoes'),
    path('contas/<int:conta_id>/movimentacoes/nova/', views_admin.admin_nova_movimentacao, name='admin_nova_movimentacao'),


]