from django.urls import path
from gestao.views import (
    admin_home,
    admin_dashboard,
    admin_clientes,
    admin_contas,
    admin_cotacoes,
    deletar_cotacao,
    admin_emissoes,
    nova_emissao,
    emissao_cliente_contexto,
    emissao_passageiro_frequente_detalhe,
    editar_emissao,
    deletar_emissao,
    admin_hoteis,
    nova_emissao_hotel,
    editar_emissao_hotel,
    deletar_emissao_hotel,
    admin_cotacoes_voo,
    nova_cotacao_voo,
    editar_cotacao_voo,
    deletar_cotacao_voo,
    visualizar_cotacao_voo,
    criar_conta,
    editar_conta,
    deletar_conta,
    admin_contas_administradas,
    criar_conta_administrada,
    editar_conta_administrada,
    deletar_conta_administrada,
    admin_programas,
    editar_programa,
    deletar_programa,
    criar_programa,
    criar_cliente,
    editar_cliente,
    admin_aeroportos,
    criar_aeroporto,
    editar_aeroporto,
    deletar_aeroporto,
    programas_do_cliente,
    programas_da_conta_administrada,
    visualizar_cliente,
    admin_movimentacoes,
    admin_nova_movimentacao,
    admin_transferir_pontos,
    cotacao_voo_pdf,
    emissao_pdf,
    emissao_detalhe,
    emissao_acompanhamento,
    marcar_notificacao_lida,
    admin_notificacoes,
    marcar_notificacao_lida_por_chave,
    marcar_notificacao_lida_por_id,
    marcar_todas_lidas,
    arquivar_notificacao,
    arquivar_por_chave,
    admin_companhias,
    criar_companhia,
    editar_companhia,
    deletar_companhia,
    admin_auditoria,
    calculadora_cotacao,
    empresas_list,
    criar_empresa,
    editar_empresa,
    configurar_empresa,
    configurar_empresa_textos,
    admin_emissores_parceiros,
    criar_emissor_parceiro,
    editar_emissor_parceiro,
    deletar_emissor_parceiro,
    emissor_parceiro_movimentacoes,
    admin_alertas_passagens,
    admin_configurar_telegram_webhook,
    governanca_plataforma,
    monitoramento_site,
    atualizar_documento_plataforma,
    criar_alerta_passagem,
    editar_alerta_passagem,
    deletar_alerta_passagem,
    alertas_passagens,
    alerta_passagem_detalhe,
    pipeline_view,
    pipeline_mover,
    api_voos_cliente,
)
from gestao.views.pipeline_hotel import pipeline_hotel_view, pipeline_hotel_mover
from gestao.views.relatorio_cliente import relatorio_cliente_pdf
from gestao.views.financeiro import (
    financeiro_empresa,
    financeiro_empresa_pagamentos,
    financeiro_empresa_contrato,
)
from gestao.views.monitoramento import (
    atualizar_status_empresa,
    atualizar_status_passagem,
    status_atualizacao_em_massa,
    ultimo_job_empresa,
)

urlpatterns = [
    path('painel/', admin_home, name='admin_dashboard'),
    path('painel/dashboard/', admin_dashboard, name='admin_dashboard_analytics'),
    path('painel/notificacoes/marcar-lida/', marcar_notificacao_lida, name='admin_marcar_notificacao_lida'),
    path('notificacoes/', admin_notificacoes, name='admin_notificacoes'),
    path('notificacoes/ler-chave/', marcar_notificacao_lida_por_chave, name='admin_notificacoes_ler_chave'),
    path('notificacoes/ler-todas/', marcar_todas_lidas, name='admin_notificacoes_ler_todas'),
    path('notificacoes/arquivar-chave/', arquivar_por_chave, name='admin_notificacoes_arquivar_chave'),
    path('notificacoes/<int:notificacao_id>/ler/', marcar_notificacao_lida_por_id, name='admin_notificacoes_ler'),
    path('notificacoes/<int:notificacao_id>/arquivar/', arquivar_notificacao, name='admin_notificacoes_arquivar'),
    path('clientes/', admin_clientes, name='admin_clientes'),
    path('clientes/<int:cliente_id>/editar/', editar_cliente, name='admin_editar_cliente'),
    path('clientes/novo/', criar_cliente, name='admin_novo_cliente'),
    path('clientes/<int:cliente_id>/programas/', programas_do_cliente, name='admin_programas_do_cliente'),
    path('clientes/<int:cliente_id>/painel/', visualizar_cliente, name='admin_visualizar_cliente'),
    path('contas/', admin_contas, name='admin_contas'),
    path('contas/novo/', criar_conta, name='admin_nova_conta'),
    path('contas/<int:conta_id>/editar/', editar_conta, name='admin_editar_conta'),
    path('contas/<int:conta_id>/deletar/', deletar_conta, name='admin_deletar_conta'),
    path('contas-administradas/', admin_contas_administradas, name='admin_contas_administradas'),
    path('contas-administradas/nova/', criar_conta_administrada, name='admin_nova_conta_administrada'),
    path('contas-administradas/<int:conta_id>/editar/', editar_conta_administrada, name='admin_editar_conta_administrada'),
    path('contas-administradas/<int:conta_id>/deletar/', deletar_conta_administrada, name='admin_deletar_conta_administrada'),
    path('contas-administradas/<int:conta_id>/programas/', programas_da_conta_administrada, name='admin_programas_da_conta_administrada'),
    path('contas/<int:conta_id>/movimentacoes/', admin_movimentacoes, name='admin_movimentacoes'),
    path('contas/<int:conta_id>/movimentacoes/transferir/', admin_transferir_pontos, name='admin_transferir_pontos'),
    path('empresas/', empresas_list, name='admin_empresas'),
    path('empresas/nova/', criar_empresa, name='admin_criar_empresa'),
    path('empresas/<int:empresa_id>/editar/', editar_empresa, name='admin_editar_empresa'),
    path('governanca/plataforma/', governanca_plataforma, name='admin_governanca_plataforma'),
    path('site/', monitoramento_site, name='admin_site_monitoramento'),
    path('governanca/plataforma/documentos/<int:documento_id>/atualizar/', atualizar_documento_plataforma, name='admin_atualizar_documento_plataforma'),
    path('empresa/configuracoes/', configurar_empresa, name='admin_empresa_configuracoes'),
    path('empresa/textos/', configurar_empresa_textos, name='admin_empresa_textos'),
    path('contas/<int:conta_id>/movimentacoes/nova/', admin_nova_movimentacao, name='admin_nova_movimentacao'),
    path('programas/', admin_programas, name='admin_programas'),
    path('programas/novo/', criar_programa, name='admin_novo_programa'),
    path('programas/<int:programa_id>/editar/', editar_programa, name='admin_editar_programa'),
    path('programas/<int:programa_id>/deletar/', deletar_programa, name='admin_deletar_programa'),
    path('aeroportos/', admin_aeroportos, name='admin_aeroportos'),
    path('aeroportos/novo/', criar_aeroporto, name='admin_novo_aeroporto'),
    path('aeroportos/<int:aeroporto_id>/editar/', editar_aeroporto, name='admin_editar_aeroporto'),
    path('aeroportos/<int:aeroporto_id>/deletar/', deletar_aeroporto, name='admin_deletar_aeroporto'),
    path('companhias/', admin_companhias, name='admin_companhias'),
    path('companhias/nova/', criar_companhia, name='admin_nova_companhia'),
    path('companhias/<int:companhia_id>/editar/', editar_companhia, name='admin_editar_companhia'),
    path('companhias/<int:companhia_id>/deletar/', deletar_companhia, name='admin_deletar_companhia'),
    path('emissores-parceiros/', admin_emissores_parceiros, name='admin_emissores_parceiros'),
    path('emissores-parceiros/novo/', criar_emissor_parceiro, name='admin_novo_emissor_parceiro'),
    path('emissores-parceiros/<int:emissor_id>/editar/', editar_emissor_parceiro, name='admin_editar_emissor_parceiro'),
    path('emissores-parceiros/<int:emissor_id>/deletar/', deletar_emissor_parceiro, name='admin_deletar_emissor_parceiro'),
    path('emissores-parceiros/<int:emissor_id>/movimentacoes/', emissor_parceiro_movimentacoes, name='admin_emissor_parceiro_movimentacoes'),
    path('cotacoes/', admin_cotacoes, name='admin_cotacoes'),
    path('cotacoes/<int:cotacao_id>/deletar/', deletar_cotacao, name='admin_deletar_cotacao'),
    path('alertas-passagens/', alertas_passagens, name='alertas_passagens'),
    path('alertas-passagens/<int:alerta_id>/', alerta_passagem_detalhe, name='alerta_passagem_detalhe'),
    path('alertas-passagens/gerenciar/', admin_alertas_passagens, name='admin_alertas_passagens'),
    path('alertas-passagens/telegram/webhook/', admin_configurar_telegram_webhook, name='admin_configurar_telegram_webhook'),
    path('alertas-passagens/gerenciar/novo/', criar_alerta_passagem, name='admin_alerta_passagem_novo'),
    path('alertas-passagens/gerenciar/<int:alerta_id>/editar/', editar_alerta_passagem, name='admin_alerta_passagem_editar'),
    path('alertas-passagens/gerenciar/<int:alerta_id>/deletar/', deletar_alerta_passagem, name='admin_alerta_passagem_deletar'),
    path('cotacoes-voo/', admin_cotacoes_voo, name='admin_cotacoes_voo'),
    path('cotacoes-voo/calculadora/', calculadora_cotacao, name='admin_calculadora_cotacao'),
    path('cotacoes-voo/nova/', nova_cotacao_voo, name='admin_nova_cotacao_voo'),
    path('cotacoes-voo/<int:cotacao_id>/editar/', editar_cotacao_voo, name='admin_editar_cotacao_voo'),
    path('cotacoes-voo/<int:cotacao_id>/deletar/', deletar_cotacao_voo, name='admin_deletar_cotacao_voo'),
    path('cotacoes-voo/<int:cotacao_id>/visualizar/', visualizar_cotacao_voo, name='admin_visualizar_cotacao_voo'),
    path('cotacoes-voo/<int:cotacao_id>/pdf/', cotacao_voo_pdf, name='admin_cotacao_voo_pdf'),
    path('emissoes/', admin_emissoes, name='admin_emissoes'),
    path('emissoes/nova/', nova_emissao, name='admin_nova_emissao'),
    path('emissoes/clientes/<int:cliente_id>/contexto/', emissao_cliente_contexto, name='admin_emissao_cliente_contexto'),
    path('emissoes/passageiros-frequentes/<int:passageiro_id>/detalhe/', emissao_passageiro_frequente_detalhe, name='admin_emissao_passageiro_frequente_detalhe'),
    path('emissoes/<int:emissao_id>/editar/', editar_emissao, name='admin_editar_emissao'),
    path('emissoes/<int:emissao_id>/deletar/', deletar_emissao, name='admin_deletar_emissao'),
    path('emissoes/<int:emissao_id>/pdf/', emissao_pdf, name='admin_emissao_pdf'),
    path('emissoes/<int:emissao_id>/detalhe/', emissao_detalhe, name='admin_emissao_detalhe'),
    path('emissoes/<int:emissao_id>/acompanhamento/', emissao_acompanhamento, name='admin_emissao_acompanhamento'),
    path('emissoes/<int:emissao_id>/atualizar-status/', atualizar_status_passagem, name='admin_emissao_atualizar_status'),
    path('monitoramento/atualizar-empresa/', atualizar_status_empresa, name='admin_monitoramento_atualizar_empresa'),
    path('monitoramento/jobs/<int:job_id>/', status_atualizacao_em_massa, name='admin_monitoramento_job_status'),
    path('monitoramento/jobs/atual/', ultimo_job_empresa, name='admin_monitoramento_job_atual'),
    path('hoteis/', admin_hoteis, name='admin_hoteis'),
    path('hoteis/nova/', nova_emissao_hotel, name='admin_nova_emissao_hotel'),
    path('hoteis/<int:emissao_id>/editar/', editar_emissao_hotel, name='admin_editar_emissao_hotel'),
    path('hoteis/<int:emissao_id>/deletar/', deletar_emissao_hotel, name='admin_deletar_emissao_hotel'),
    path('auditoria/', admin_auditoria, name='admin_auditoria'),
    path('pipeline/', pipeline_view, name='admin_pipeline'),
    path('pipeline/mover/', pipeline_mover, name='admin_pipeline_mover'),
    path('pipeline-hotel/', pipeline_hotel_view, name='admin_pipeline_hotel'),
    path('pipeline-hotel/mover/', pipeline_hotel_mover, name='admin_pipeline_hotel_mover'),
    path('api/voos-cliente/<int:cliente_id>/', api_voos_cliente, name='api_voos_cliente'),
    path('clientes/<int:cliente_id>/relatorio-pdf/', relatorio_cliente_pdf, name='admin_relatorio_cliente_pdf'),

    # Financeiro da agencia (B2B SaaS — lado tenant)
    path('financeiro/', financeiro_empresa, name='admin_financeiro'),
    path('financeiro/pagamentos/', financeiro_empresa_pagamentos, name='admin_financeiro_pagamentos'),
    path('financeiro/contrato/', financeiro_empresa_contrato, name='admin_financeiro_contrato'),
]
