# Generated by Django 5.2.4 on 2026-04-21 02:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(db_index=True, help_text='Primeiro dia do mes a que o custo se refere (YYYY-MM-01).')),
                ('categoria', models.CharField(choices=[('infra', 'Infraestrutura (Railway, Cloudflare)'), ('ia', 'IA (OpenAI, Anthropic)'), ('dominio', 'Dominio / SSL'), ('marketing', 'Marketing / Ads'), ('ferramentas', 'Ferramentas SaaS'), ('pessoal', 'Pessoal / Servicos'), ('outros', 'Outros')], db_index=True, default='outros', max_length=20)),
                ('fornecedor', models.CharField(max_length=120)),
                ('descricao', models.CharField(blank=True, default='', max_length=240)),
                ('moeda', models.CharField(choices=[('BRL', 'Real (BRL)'), ('USD', 'Dolar (USD)')], default='BRL', max_length=3)),
                ('valor_original', models.DecimalField(decimal_places=2, help_text='Valor na moeda original.', max_digits=12)),
                ('cambio_ptax', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Cambio PTAX do dia do pagamento. 1.0000 quando BRL.', max_digits=10)),
                ('iof', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IOF pago (3,5% em cartao internacional, zero em BRL).', max_digits=10)),
                ('valor_brl', models.DecimalField(decimal_places=2, help_text='Valor total em BRL (valor_original * cambio + iof).', max_digits=12)),
                ('tem_invoice', models.BooleanField(default=False, help_text='Se o fornecedor emitiu invoice/receipt valido.')),
                ('anexo', models.FileField(blank=True, help_text='PDF da invoice/recibo (opcional).', null=True, upload_to='ncadm/custos/%Y/%m/')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custo operacional',
                'verbose_name_plural': 'Custos operacionais',
                'ordering': ['-mes_referencia', 'categoria', 'fornecedor'],
                'indexes': [models.Index(fields=['mes_referencia', 'categoria'], name='superadmin__mes_ref_a3bce7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ObrigacaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('das', 'DAS (Simples Nacional)'), ('defis', 'DEFIS anual'), ('nfse', 'Emissao NFS-e'), ('dctfweb', 'DCTFWeb / eSocial mensal'), ('esocial', 'eSocial'), ('dasn_simei', 'DASN-SIMEI (MEI)'), ('outra', 'Outra')], default='outra', max_length=20)),
                ('descricao', models.CharField(max_length=180)),
                ('competencia', models.DateField(help_text='Mes/ano de competencia (YYYY-MM-01).')),
                ('vencimento', models.DateField(db_index=True)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga / Entregue'), ('atrasada', 'Atrasada')], db_index=True, default='pendente', max_length=20)),
                ('pago_em', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obrigacao fiscal',
                'verbose_name_plural': 'Obrigacoes fiscais',
                'ordering': ['vencimento'],
                'indexes': [models.Index(fields=['status', 'vencimento'], name='superadmin__status_30d791_idx')],
            },
        ),
    ]
