# Generated by Django 5.2.4 on 2026-04-21 03:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, default='', max_length=180)),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=120)),
                ('cnpj', models.CharField(blank=True, default='', help_text='00.000.000/0000-00', max_length=18)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, default='', max_length=240)),
                ('municipio', models.CharField(blank=True, default='', max_length=80)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('regime_atual', models.CharField(choices=[('inova_simples', 'Inova Simples (I.S.)'), ('mei', 'MEI'), ('me_simples', 'ME - Simples Nacional'), ('epp_simples', 'EPP - Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], default='inova_simples', max_length=20)),
                ('anexo_simples', models.CharField(blank=True, default='', help_text='Anexo do Simples Nacional aplicavel (III, IV, V). SaaS geralmente Anexo III.', max_length=5)),
                ('cnae_principal', models.CharField(blank=True, default='', help_text='Ex.: 6202-3/00 - Desenvolvimento e licenciamento de software customizavel.', max_length=20)),
                ('cnaes_secundarios', models.TextField(blank=True, default='', help_text='Um CNAE por linha.')),
                ('inscricao_municipal', models.CharField(blank=True, default='', max_length=40)),
                ('inscricao_estadual', models.CharField(blank=True, default='', max_length=40)),
                ('iss_aliquota', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Aliquota de ISS em % (ex.: 2.00, 5.00).', max_digits=5)),
                ('nfse_portal_url', models.URLField(blank=True, default='')),
                ('contador_nome', models.CharField(blank=True, default='', max_length=120)),
                ('contador_crc', models.CharField(blank=True, default='', max_length=30)),
                ('contador_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contador_telefone', models.CharField(blank=True, default='', max_length=30)),
                ('contador_escritorio', models.CharField(blank=True, default='', max_length=120)),
                ('regime_alvo', models.CharField(blank=True, choices=[('inova_simples', 'Inova Simples (I.S.)'), ('mei', 'MEI'), ('me_simples', 'ME - Simples Nacional'), ('epp_simples', 'EPP - Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], default='', help_text='Regime para o qual a empresa esta migrando (se houver).', max_length=20)),
                ('conversao_status', models.CharField(choices=[('nao_iniciada', 'Nao iniciada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida')], default='nao_iniciada', max_length=20)),
                ('conversao_iniciada_em', models.DateField(blank=True, null=True)),
                ('conversao_prevista_para', models.DateField(blank=True, null=True)),
                ('conversao_concluida_em', models.DateField(blank=True, null=True)),
                ('conversao_checklist', models.TextField(blank=True, default='', help_text='Checklist livre (um item por linha). Prefixar com [x] para concluidos.')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil fiscal',
                'verbose_name_plural': 'Perfil fiscal',
            },
        ),
    ]
