# Generated by Django 5.2.4 on 2026-04-21 04:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_perfilfiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, help_text='Data em que o valor caiu na conta.')),
                ('mes_competencia', models.DateField(db_index=True, help_text='Primeiro dia do mes de competencia (YYYY-MM-01). Preenchido automaticamente.')),
                ('cliente', models.CharField(blank=True, default='', max_length=180)),
                ('natureza', models.CharField(choices=[('saas', 'Assinatura SaaS B2B'), ('servico', 'Servico avulso'), ('outro', 'Outro')], default='saas', max_length=20)),
                ('origem', models.CharField(choices=[('adquirente', 'Adquirente (Stripe, Asaas, MP)'), ('pix', 'Pix direto'), ('boleto', 'Boleto'), ('ted', 'TED / transferencia'), ('outro', 'Outro')], default='adquirente', max_length=20)),
                ('valor_bruto', models.DecimalField(decimal_places=2, help_text='Valor bruto recebido (base para o Simples).', max_digits=12)),
                ('taxa_adquirente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taxa descontada pelo adquirente (informativa, NAO reduz o Simples).', max_digits=12)),
                ('descricao', models.CharField(blank=True, default='', max_length=240)),
                ('nfse_emitida', models.BooleanField(default=False, help_text='Se a NFS-e correspondente ja foi emitida na prefeitura.')),
                ('nfse_numero', models.CharField(blank=True, default='', max_length=40)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recebimento de receita',
                'verbose_name_plural': 'Recebimentos de receita',
                'ordering': ['-data', '-criado_em'],
                'indexes': [models.Index(fields=['mes_competencia', 'natureza'], name='superadmin__mes_com_73cf05_idx')],
            },
        ),
    ]
