# Generated by Django 5.2.4 on 2026-04-16 20:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao', '0072_empresa_cnpj_empresa_documento_titular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limite_operadores', models.PositiveIntegerField(default=3)),
                ('limite_clientes', models.PositiveIntegerField(default=0, help_text='0 = ilimitado')),
                ('features', models.JSONField(blank=True, default=dict)),
                ('trial_dias', models.PositiveIntegerField(default=14)),
                ('ativo', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False, help_text='Plano recomendado (destaque visual)')),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['ordem', 'preco_mensal'],
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('ativa', 'Ativa'), ('inadimplente', 'Inadimplente'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada')], db_index=True, default='trial', max_length=20)),
                ('gateway_customer_id', models.CharField(blank=True, max_length=120)),
                ('gateway_subscription_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('trial_fim', models.DateTimeField(blank=True, null=True)),
                ('data_vencimento', models.DateTimeField(blank=True, null=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('ref_vendedor', models.CharField(blank=True, help_text='Codigo do vendedor que indicou', max_length=60)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='gestao.empresa')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='onboarding.plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('falhou', 'Falhou'), ('estornado', 'Estornado')], db_index=True, default='pendente', max_length=20)),
                ('metodo', models.CharField(blank=True, choices=[('cartao', 'Cartao de credito'), ('pix', 'PIX'), ('boleto', 'Boleto')], max_length=20)),
                ('gateway_ref', models.CharField(db_index=True, max_length=120, unique=True)),
                ('gateway_event_type', models.CharField(blank=True, max_length=80)),
                ('dados_gateway', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='onboarding.assinatura')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
