# Generated by Django 5.2.4 on 2025-07-25 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParametroConversao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_por_1000_pontos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.programafidelidade')),
            ],
        ),
        migrations.CreateModel(
            name='EmissaoPassagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField()),
                ('pontos_utilizados', models.IntegerField()),
                ('valor_passagem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('economia_obtida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalhes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.cliente')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.programafidelidade')),
            ],
        ),
        migrations.CreateModel(
            name='ContaFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_pontos', models.IntegerField(default=0)),
                ('validade', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.cliente')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.programafidelidade')),
            ],
        ),
    ]
