# Generated by Django 5.2.4 on 2025-07-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], default='cliente', max_length=10),
        ),
    ]
