# Generated by Django 5.2.4 on 2025-07-29 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=5, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='ValorMilheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_nome', models.CharField(max_length=50, unique=True)),
                ('valor_mercado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('atualizado_em', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contafidelidade',
            old_name='saldo_pontos',
            new_name='pontos_clube_mes',
        ),
        migrations.RenameField(
            model_name='emissaopassagem',
            old_name='data_emissao',
            new_name='data_ida',
        ),
        migrations.RenameField(
            model_name='emissaopassagem',
            old_name='valor_passagem',
            new_name='valor_pago',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
        migrations.AddField(
            model_name='cliente',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador'), ('cliente', 'Cliente')], default='cliente', max_length=10),
        ),
        migrations.AddField(
            model_name='contafidelidade',
            name='clube_periodicidade',
            field=models.CharField(choices=[('nenhum', 'Nenhum'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='nenhum', max_length=12),
        ),
        migrations.AddField(
            model_name='contafidelidade',
            name='data_inicio_clube',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contafidelidade',
            name='valor_assinatura_clube',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='emissaopassagem',
            name='data_volta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissaopassagem',
            name='qtd_passageiros',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissaopassagem',
            name='valor_referencia',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissaopassagem',
            name='valor_referencia_pontos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='programafidelidade',
            name='preco_medio_milheiro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_gestao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emissaopassagem',
            name='economia_obtida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='emissaopassagem',
            name='pontos_utilizados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emissaopassagem',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.programafidelidade'),
        ),
        migrations.AddField(
            model_name='emissaopassagem',
            name='aeroporto_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='gestao.aeroporto'),
        ),
        migrations.AddField(
            model_name='emissaopassagem',
            name='aeroporto_partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='gestao.aeroporto'),
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('pontos', models.IntegerField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='gestao.contafidelidade')),
            ],
        ),
        migrations.DeleteModel(
            name='ParametroConversao',
        ),
    ]
