# Generated by Django 5.2.4 on 2025-07-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_aeroporto_valormilheiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeroporto',
            name='cidade',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aeroporto',
            name='estado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aeroporto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aeroporto',
            name='sigla',
            field=models.CharField(max_length=10),
        ),
    ]
