# Generated by Django 5.2.4 on 2025-07-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_aeroporto_cidade_aeroporto_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='descricao',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
