# Generated by Django 5.2.4 on 2025-07-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_emissaopassagem_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissaopassagem',
            name='data_emissao',
        ),
        migrations.RemoveField(
            model_name='emissaopassagem',
            name='valor_passagem',
        ),
        migrations.AlterField(
            model_name='emissaopassagem',
            name='data_ida',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emissaopassagem',
            name='data_volta',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
