# Generated by Django 5.2.4 on 2025-07-30 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_alter_movimentacao_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissaopassagem',
            name='companhia_aerea',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emissaopassagem',
            name='localizador',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='EmissaoHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_hotel', models.CharField(max_length=200)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('valor_referencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('economia_obtida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.cliente')),
            ],
        ),
    ]
