# Generated by Django 5.2.4 on 2025-07-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_remove_emissaopassagem_data_emissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissaopassagem',
            name='data_volta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
