# Generated by Django 5.2.4 on 2025-07-26 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_emissaopassagem_data_volta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contafidelidade',
            name='assinante_clube',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contafidelidade',
            name='pontos_clube_mes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contafidelidade',
            name='valor_assinatura_clube',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contafidelidade',
            name='valor_total_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='MovimentacaoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pontos', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='gestao.contafidelidade')),
            ],
        ),
    ]
