# Generated by Django 5.2.4 on 2025-07-31 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0006_acessoclientelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrechoEmissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=1)),
                ("companhia_aerea", models.CharField(blank=True, max_length=100)),
                ("numero_voo", models.CharField(blank=True, max_length=50)),
                ("saida", models.DateTimeField()),
                ("chegada", models.DateTimeField()),
                ("classe_tarifaria", models.CharField(blank=True, max_length=50)),
                ("assento", models.CharField(blank=True, max_length=20)),
                ("situacao", models.CharField(default="Confirmado", max_length=30)),
                (
                    "aeroporto_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinos_trecho",
                        to="gestao.aeroporto",
                    ),
                ),
                (
                    "aeroporto_origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origens_trecho",
                        to="gestao.aeroporto",
                    ),
                ),
                (
                    "emissao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trechos",
                        to="gestao.emissaopassagem",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
    ]
