# Generated by Django 5.2.4 on 2025-07-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_contafidelidade_assinante_clube_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contafidelidade',
            name='assinante_clube',
        ),
        migrations.AddField(
            model_name='contafidelidade',
            name='clube_periodicidade',
            field=models.CharField(choices=[('nenhum', 'Nenhum'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='nenhum', max_length=12),
        ),
        migrations.AddField(
            model_name='contafidelidade',
            name='data_inicio_clube',
            field=models.DateField(blank=True, null=True),
        ),
    ]
