# Generated by Django 5.2.4 on 2025-07-31 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0006_acessoclientelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="CotacaoVoo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("companhia_aerea", models.CharField(blank=True, max_length=100)),
                ("data_voo", models.DateField()),
                ("qtd_passageiros", models.PositiveIntegerField(default=1)),
                ("classe", models.CharField(blank=True, max_length=50)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "valor_passagem",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "taxas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("milhas", models.IntegerField(default=0)),
                (
                    "valor_milheiro",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("parcelas", models.IntegerField(default=1)),
                (
                    "juros",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "valor_parcelado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "valor_vista",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("validade", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aceita", "Aceita"),
                            ("rejeitada", "Rejeitada"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gestao.cliente"
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotacoes_destino",
                        to="gestao.aeroporto",
                    ),
                ),
                (
                    "origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotacoes_origem",
                        to="gestao.aeroporto",
                    ),
                ),
            ],
        ),
    ]
