# Generated by Django 5.2.4 on 2025-07-31 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0007_cotacaovoo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotacaovoo",
            name="emissao",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestao.emissaopassagem",
            ),
        ),
        migrations.AlterField(
            model_name="cotacaovoo",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aceita", "Aceita"),
                    ("rejeitada", "Rejeitada"),
                    ("emissao", "Emissão"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
