# Generated by Django 5.2.4 on 2025-07-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_remove_contafidelidade_assinante_clube_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovimentacaoPontos',
        ),
    ]
