# Generated by Django 5.2.4 on 2025-08-01 00:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0008_cotacaovoo_emissao_alter_cotacaovoo_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cotacaovoo",
            name="data_voo",
        ),
        migrations.AddField(
            model_name="cotacaovoo",
            name="data_ida",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cotacaovoo",
            name="data_volta",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cotacaovoo",
            name="programa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestao.programafidelidade",
            ),
        ),
    ]
