# Generated by Django 5.2.4 on 2025-07-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_delete_movimentacaopontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contafidelidade',
            name='valor_por_1000_pontos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='MovimentacaoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pontos', models.IntegerField(help_text='Positivo para adicionar, negativo para remover')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='gestao.contafidelidade')),
            ],
        ),
        migrations.DeleteModel(
            name='ParametroConversao',
        ),
    ]
