# Generated by Django 5.2.4 on 2025-08-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0009_remove_cotacaovoo_data_voo_cotacaovoo_data_ida_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissaopassagem",
            name="data_ida",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="emissaopassagem",
            name="data_volta",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
