# Generated by Django 5.2.4 on 2025-07-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_contafidelidade_valor_por_1000_pontos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contafidelidade',
            name='saldo_pontos',
            field=models.IntegerField(default=0, help_text='(pode ser sobrescrito pelas movimentações)'),
        ),
        migrations.AlterField(
            model_name='contafidelidade',
            name='valor_por_1000_pontos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cotação do milheiro', max_digits=10),
        ),
        migrations.AlterField(
            model_name='contafidelidade',
            name='valor_total_pago',
            field=models.DecimalField(decimal_places=2, default=0, help_text='(pode ser sobrescrito pelas movimentações)', max_digits=10),
        ),
    ]
