# Generated by Django 5.2.4 on 2025-07-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_alter_contafidelidade_saldo_pontos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contafidelidade',
            name='saldo_pontos',
        ),
        migrations.RemoveField(
            model_name='contafidelidade',
            name='valor_por_1000_pontos',
        ),
        migrations.RemoveField(
            model_name='contafidelidade',
            name='valor_total_pago',
        ),
    ]
