# Generated by Django 5.2.4 on 2025-08-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_alter_emissaopassagem_data_ida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacaovoo',
            name='economia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotacaovoo',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotacaovoo',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
