# Generated by Django 5.2.4 on 2025-07-27 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_remove_contafidelidade_saldo_pontos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorMilheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_nome', models.CharField(max_length=50, unique=True)),
                ('valor_mercado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('atualizado_em', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_gestao', to=settings.AUTH_USER_MODEL),
        ),
    ]
