# Generated by Django 5.2.4 on 2025-08-02 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0011_cotacaovoo_economia_alter_cotacaovoo_desconto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissaopassagem",
            name="aeroporto_escala",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalas",
                to="gestao.aeroporto",
            ),
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="duracao_escala",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="possui_escala",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="qtd_adultos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="qtd_bebes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="qtd_criancas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="emissaopassagem",
            name="qtd_passageiros",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Passageiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("documento", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("adulto", "Adulto"),
                            ("crianca", "Criança"),
                            ("bebe", "Bebê"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "emissao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passageiros",
                        to="gestao.emissaopassagem",
                    ),
                ),
            ],
        ),
    ]
