# Generated by Django 5.2.4 on 2025-07-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0012_valormilheiro_alter_cliente_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]