# Generated by Django 5.2.4 on 2025-08-02 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0012_emissaopassagem_aeroporto_escala_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emissaopassagem",
            name="aeroporto_escala",
        ),
        migrations.RemoveField(
            model_name="emissaopassagem",
            name="duracao_escala",
        ),
        migrations.RemoveField(
            model_name="emissaopassagem",
            name="possui_escala",
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="qtd_escalas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Escala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duracao", models.DurationField()),
                ("cidade", models.CharField(blank=True, max_length=100)),
                (
                    "aeroporto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao.aeroporto",
                    ),
                ),
                (
                    "emissao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalas",
                        to="gestao.emissaopassagem",
                    ),
                ),
            ],
        ),
    ]
