# Generated by Django 5.2.4 on 2025-08-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_remove_emissaopassagem_aeroporto_escala_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanhiaAerea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('site_url', models.URLField(blank=True, null=True, verbose_name='Link para consulta de reserva')),
            ],
            options={
                'verbose_name': 'Companhia Aérea',
                'verbose_name_plural': 'Companhias Aéreas',
                'ordering': ['nome'],
            },
        ),
    ]
