# Generated by Django 5.2.4 on 2025-07-28 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0013_cliente_ativo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aeroporto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigla", models.CharField(max_length=5, unique=True)),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["sigla"],
            },
        ),
        migrations.RemoveField(
            model_name="emissaopassagem",
            name="aeroporto_ida",
        ),
        migrations.RemoveField(
            model_name="emissaopassagem",
            name="aeroporto_volta",
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="aeroporto_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destinos",
                to="gestao.aeroporto",
            ),
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="aeroporto_partida",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partidas",
                to="gestao.aeroporto",
            ),
        ),
    ]