# Generated by Django 5.2.4 on 2025-08-02 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0014_companhiaaerea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissaopassagem",
            name="companhia_aerea",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emissoes",
                to="gestao.companhiaaerea",
            ),
        ),
    ]
