# Generated by Django 4.2 on 2025-08-03 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestao", "0016_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios_criados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
