# Generated by Django 5.2.4 on 2025-08-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0016_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissaopassagem',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
