# Generated by Django 5.2.4 on 2025-08-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0017_cliente_criado_por'),
        ('gestao', '0017_emissaopassagem_descricao'),
    ]

    operations = [
    ]
