# Generated by Django 5.2.4 on 2025-08-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0018_merge_20250802_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissaopassagem',
            name='descricao',
        ),
    ]
