# Generated by Django 5.2.4 on 2025-08-03 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0019_remove_emissaopassagem_descricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("limite_administradores", models.PositiveIntegerField(default=0)),
                ("limite_operadores", models.PositiveIntegerField(default=0)),
                ("limite_clientes", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="cliente",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes",
                to="gestao.empresa",
            ),
        ),
    ]
