# Generated by Django 5.2.4 on 2025-12-20 17:48

import re
from django.db import migrations, models


def normalize_cpfs(apps):
    Cliente = apps.get_model("gestao", "Cliente")
    for cliente in Cliente.objects.all():
        digits = re.sub(r"\D", "", cliente.cpf or "")
        if digits:
            cliente.cpf = digits
            cliente.save(update_fields=["cpf"])


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0020_empresa_and_cliente_empresa"),
    ]

    operations = [
        migrations.RunPython(
            code=normalize_cpfs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
