# Generated by Django 5.2.4 on 2025-08-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0020_empresa_cliente_empresa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="cpf",
        ),
        migrations.AddField(
            model_name="cliente",
            name="data_expiracao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="documento",
            field=models.CharField(default="", max_length=18),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo_documento",
            field=models.CharField(
                choices=[("cpf", "CPF"), ("cnpj", "CNPJ")], default="cpf", max_length=4
            ),
        ),
    ]
