# Generated by Django 5.2.4 on 2025-12-21 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0021_alter_cliente_cpf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="escala",
            options={"ordering": ["tipo", "ordem", "id"]},
        ),
        migrations.AddField(
            model_name="escala",
            name="cotacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalas",
                to="gestao.cotacaovoo",
            ),
        ),
        migrations.AddField(
            model_name="escala",
            name="ordem",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="escala",
            name="tipo",
            field=models.CharField(
                choices=[("ida", "Ida"), ("volta", "Volta")],
                default="ida",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="escala",
            name="emissao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalas",
                to="gestao.emissaopassagem",
            ),
        ),
    ]
