# Generated by Django 5.2.4 on 2025-08-03 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0021_remove_cliente_cpf_cliente_data_expiracao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="administrador_responsavel",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"perfil": "admin"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinados",
                to="gestao.cliente",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="operador_responsavel",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"perfil": "operador"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_associados",
                to="gestao.cliente",
            ),
        ),
    ]
