# Generated by Django 5.2.4 on 2025-12-21 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0022_alter_escala_options_escala_cotacao_escala_ordem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programafidelidade",
            name="programa_base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programas_vinculados",
                to="gestao.programafidelidade",
            ),
        ),
        migrations.AddField(
            model_name="programafidelidade",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("principal", "Programa principal"),
                    ("vinculado", "Programa vinculado"),
                ],
                default="principal",
                max_length=20,
            ),
        ),
    ]
