# Generated by Django 5.2.4 on 2025-12-21 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0023_programafidelidade_programa_base_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contafidelidade",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestao.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="cotacaovoo",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestao.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="emissaopassagem",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestao.cliente",
            ),
        ),
        migrations.CreateModel(
            name="ContaAdministrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("observacoes", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contas_administradas",
                        to="gestao.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta Administrada",
                "verbose_name_plural": "Contas Administradas",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="contafidelidade",
            name="conta_administrada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contas_fidelidade",
                to="gestao.contaadministrada",
            ),
        ),
        migrations.AddField(
            model_name="cotacaovoo",
            name="conta_administrada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cotacoes",
                to="gestao.contaadministrada",
            ),
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="conta_administrada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emissoes",
                to="gestao.contaadministrada",
            ),
        ),
    ]
