# Generated by Django 5.2.4 on 2025-12-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0024_alter_contafidelidade_cliente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contafidelidade",
            name="login_programa",
            field=models.CharField(
                blank=True,
                help_text="Login do titular junto ao programa",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="contafidelidade",
            name="senha_programa",
            field=models.CharField(
                blank=True,
                help_text="Senha do titular junto ao programa",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="contafidelidade",
            name="titular_programa_info",
            field=models.TextField(
                blank=True,
                help_text="Informações adicionais do titular (ex.: nome completo, CPF, dados de resgate)",
            ),
        ),
    ]
