# Generated by Django 5.2.4 on 2025-12-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0025_contafidelidade_login_programa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programafidelidade",
            name="quantidade_cpfs_disponiveis",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quantidade total de CPFs disponíveis no programa",
                null=True,
            ),
        ),
    ]
