# Generated by Django 5.2.4 on 2025-12-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0026_programafidelidade_quantidade_cpfs_disponiveis"),
    ]

    operations = [
        migrations.AddField(
            model_name="contafidelidade",
            name="observacoes_programa",
            field=models.TextField(
                blank=True,
                help_text="Observações gerais sobre o uso do programa para esta conta",
            ),
        ),
        migrations.AddField(
            model_name="contafidelidade",
            name="quantidade_cpfs_disponiveis",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quantidade de CPFs que ainda podem ser utilizados com este programa. Deixe vazio para ilimitado.",
                null=True,
            ),
        ),
    ]
