# Generated by Django 5.2.4 on 2025-12-31 00:24

import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0027_contafidelidade_observacoes_programa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmissorParceiro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=150)),
                ("ativo", models.BooleanField(default=True)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="emissores_parceiros", to="gestao.empresa")),
            ],
            options={
                "verbose_name": "Emissor Parceiro",
                "verbose_name_plural": "Emissores Parceiros",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PassageiroFrequente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=14)),
                ("rg", models.CharField(blank=True, max_length=50)),
                ("passaporte", models.CharField(blank=True, max_length=30)),
                ("passaporte_validade", models.DateField(blank=True, null=True)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="passageiros_frequentes", to="gestao.cliente")),
            ],
            options={
                "verbose_name": "Passageiro Frequente",
                "verbose_name_plural": "Passageiros Frequentes",
                "ordering": ["nome"],
            },
        ),
        migrations.RenameField(
            model_name="passageiro",
            old_name="documento",
            new_name="cpf",
        ),
        migrations.AlterField(
            model_name="passageiro",
            name="cpf",
            field=models.CharField(max_length=14),
        ),
        migrations.AddField(
            model_name="passageiro",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passageiro",
            name="observacoes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="passageiro",
            name="passaporte",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="passageiro",
            name="passaporte_validade",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passageiro",
            name="rg",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="emissor_parceiro",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="emissoes", to="gestao.emissorparceiro"),
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="lucro",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="valor_milheiro_parceiro",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="valor_venda_final",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="emissorparceiro",
            name="programas",
            field=models.ManyToManyField(blank=True, related_name="emissores_parceiros", to="gestao.programafidelidade"),
        ),
    ]
