# Generated by Django 5.2.4 on 2026-01-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0030_alerta_viagem_notificacao_sistema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertaviagem",
            name="conteudo",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="alertaviagem",
            name="continente",
            field=models.CharField(
                choices=[
                    ("Europa", "Europa"),
                    ("América do Sul", "América do Sul"),
                    ("América do Norte", "América do Norte"),
                    ("Ásia", "Ásia"),
                    ("África", "África"),
                    ("Oceania", "Oceania"),
                ],
                max_length=60,
            ),
        ),
    ]
