# Generated by Django 5.2.4 on 2026-03-23 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0033_emissaopassagem_valor_total_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="passageirofrequente",
            name="relacao",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="programafidelidade",
            name="dias_reset",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Obrigatório quando a regra de reset for baseada em dias.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programafidelidade",
            name="limite_cpfs",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Limite configurável de CPFs por conta fidelidade para este programa.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programafidelidade",
            name="tipo_regra_reset",
            field=models.CharField(
                choices=[("dias", "Dias"), ("ano", "Ano civil")],
                default="ano",
                help_text="Define quando um CPF volta a ficar disponível para reutilização.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="UsoCPF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=11)),
                ("data_ultima_emissao", models.DateField()),
                (
                    "conta_fidelidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos_cpf",
                        to="gestao.contafidelidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uso de CPF",
                "verbose_name_plural": "Usos de CPF",
                "ordering": ["cpf"],
                "unique_together": {("conta_fidelidade", "cpf")},
            },
        ),
    ]
