# Generated by Django 5.2.4 on 2026-03-26 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0034_passageirofrequente_relacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissaopassagem",
            name="custo_emissor",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="hotel_vinculado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emissoes_vinculadas",
                to="gestao.emissaohotel",
            ),
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="milhas_do_cliente",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emissaopassagem",
            name="valor_cobrado_cliente",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="passageirofrequente",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("adulto", "Adulto"),
                    ("crianca", "Criança"),
                    ("adolescente", "Adolescente"),
                ],
                default="adulto",
                max_length=20,
            ),
        ),
    ]
