# Generated by Django 5.2.4 on 2026-04-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0037_programafidelidade_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissaopassagem',
            name='bagagem_despachada',
            field=models.CharField(blank=True, choices=[('nao_inclusa', 'Nao inclusa'), ('1x23', '1 bagagem despachada ate 23kg'), ('2x23', '2 bagagens despachadas ate 23kg'), ('1x32', '1 bagagem despachada ate 32kg')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='emissaopassagem',
            name='bagagem_mao',
            field=models.CharField(blank=True, choices=[('item_pessoal', 'Item pessoal'), ('mao_10kg', 'Item pessoal + bagagem de mao ate 10kg'), ('mao_12kg', 'Item pessoal + bagagem de mao ate 12kg')], default='', max_length=32),
        ),
    ]
