# Generated by Django 5.2.4 on 2026-04-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0038_emissaopassagem_bagagem_despachada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='descricao_rodape',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='empresa',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
