# Generated by Django 5.2.4 on 2026-04-01 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0039_empresa_cidade_empresa_descricao_rodape_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoPassagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_consulta', models.CharField(choices=[('manual', 'Atualizacao manual'), ('sistema_origem', 'Sistema de origem'), ('portal_companhia', 'Portal da companhia'), ('api_voo', 'API de voo')], default='manual', max_length=24)),
                ('sistema_origem', models.CharField(blank=True, max_length=120)),
                ('referencia_externa', models.CharField(blank=True, max_length=120)),
                ('localizador_consulta', models.CharField(blank=True, max_length=100)),
                ('sobrenome_consulta', models.CharField(blank=True, max_length=120)),
                ('email_consulta', models.EmailField(blank=True, max_length=254)),
                ('status_reserva', models.CharField(choices=[('nao_iniciado', 'Nao iniciado'), ('aguardando_consulta', 'Aguardando consulta'), ('reservado', 'Reservado'), ('emitido', 'Emitido'), ('ticketado', 'Ticketado'), ('alterado', 'Alterado'), ('cancelado', 'Cancelado'), ('embarcado', 'Embarcado'), ('concluido', 'Concluido'), ('inconsistente', 'Inconsistente')], default='nao_iniciado', max_length=24)),
                ('status_voo', models.CharField(choices=[('nao_consultado', 'Nao consultado'), ('programado', 'Programado'), ('checkin_aberto', 'Check-in aberto'), ('embarque_aberto', 'Embarque aberto'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado'), ('embarcado', 'Embarcado'), ('concluido', 'Concluido')], default='nao_consultado', max_length=24)),
                ('ultimo_resumo', models.TextField(blank=True)),
                ('orientacao_operacional', models.TextField(blank=True)),
                ('payload_bruto_json', models.JSONField(blank=True, default=dict)),
                ('ultima_sincronizacao_em', models.DateTimeField(blank=True, null=True)),
                ('proxima_verificacao_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('emissao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamento', to='gestao.emissaopassagem')),
            ],
            options={
                'verbose_name': 'Acompanhamento de passagem',
                'verbose_name_plural': 'Acompanhamentos de passagens',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
