# Generated by Django 5.2.4 on 2026-04-03 12:10

import django.core.validators
import gestao.models.empresa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0049_aceitedocumentoplataforma_device_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo_documentos',
            field=models.FileField(blank=True, help_text='PNG horizontal com fundo transparente, recomendado 1200x400px e ate 150KB.', null=True, upload_to='empresas/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), gestao.models.empresa.validate_company_logo]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ocultar_logo_documentos',
            field=models.BooleanField(default=False),
        ),
    ]
