# Generated by Django 5.2.4 on 2026-04-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0050_empresa_logo_documentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cotacao_condicoes_gerais',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cotacao_hint_economia',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cotacao_hint_taxa_embarque',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cotacao_hint_valor_encontrado',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cotacao_hint_valor_parcelado',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cotacao_hint_valor_referencia',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cotacao_hint_valor_total',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cotacao_observacao_padrao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='emissao_bagagem_despachada_hint',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='emissao_bagagem_mao_hint',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='emissao_cta_companhia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='emissao_hint_taxa_embarque',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='emissao_hint_taxa_servico',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='emissao_hint_valor_total',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='emissao_observacao_confirmada',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='emissao_observacao_pendente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='emissao_orientacoes',
            field=models.TextField(blank=True),
        ),
    ]
