# Generated by Django 5.2.4 on 2026-04-03 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0051_empresa_cotacao_condicoes_gerais_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaosistema',
            name='chave',
            field=models.CharField(blank=True, db_index=True, max_length=191),
        ),
        migrations.AddField(
            model_name='notificacaosistema',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_sistema', to='gestao.empresa'),
        ),
        migrations.AddField(
            model_name='notificacaosistema',
            name='lida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacaosistema',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notificacaosistema',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_sistema', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacaosistema',
            name='mensagem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificacaosistema',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='notificacaosistema',
            constraint=models.UniqueConstraint(condition=models.Q(('chave', ''), _negated=True), fields=('usuario', 'chave'), name='unique_notificacao_sistema_usuario_chave'),
        ),
    ]
