# Generated by Django 5.2.4 on 2026-04-04 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0052_notificacaosistema_chave_notificacaosistema_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoplataforma',
            name='data_vigencia',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='programafidelidade',
            name='dias_reset',
            field=models.PositiveIntegerField(blank=True, help_text='Obrigatorio quando a regra de reset for baseada em dias.', null=True),
        ),
        migrations.AlterField(
            model_name='programafidelidade',
            name='limite_cpfs',
            field=models.PositiveIntegerField(blank=True, help_text='Limite configuravel de CPFs por conta fidelidade para este programa.', null=True),
        ),
        migrations.AlterField(
            model_name='programafidelidade',
            name='quantidade_cpfs_disponiveis',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade total de CPFs disponiveis no programa', null=True),
        ),
        migrations.AlterField(
            model_name='programafidelidade',
            name='tipo_regra_reset',
            field=models.CharField(choices=[('dias', 'Dias'), ('ano', 'Ano civil')], default='ano', help_text='Define quando um CPF volta a ficar disponivel para reutilizacao.', max_length=10),
        ),
    ]
