# Generated by Django 5.2.4 on 2026-04-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0053_alter_documentoplataforma_data_vigencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissaopassagem',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='emissoes/comprovantes/', verbose_name='Comprovante'),
        ),
    ]
