# Generated by Django 5.2.4 on 2026-04-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0054_emissaopassagem_comprovante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissaopassagem',
            name='comprovante',
        ),
        migrations.AlterField(
            model_name='cotacaovoo',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotacaovoo',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotacaovoo',
            name='milhas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
