# Generated by Django 5.2.4 on 2026-04-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0055_cotacaovoo_fix_milhas_juros_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacaovoo',
            name='valor_referencia_manual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se preenchido, sobrescreve o valor de referencia calculado automaticamente.', max_digits=10, null=True),
        ),
    ]
