# Generated by Django 5.2.4 on 2026-04-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0056_cotacaovoo_valor_referencia_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissaopassagem',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='emissoes/comprovantes/', verbose_name='Comprovante de pagamento'),
        ),
    ]
