# Generated by Django 5.2.4 on 2026-04-08 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_leadalertaemail"),
        ("gestao", "0057_emissaopassagem_comprovante_pagamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramNoticiaEvento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("update_id", models.BigIntegerField(unique=True)),
                ("chat_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("message_id", models.BigIntegerField(blank=True, null=True)),
                ("chat_nome", models.CharField(blank=True, max_length=255)),
                ("remetente", models.CharField(blank=True, max_length=255)),
                ("mensagem_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("texto_bruto", models.TextField(blank=True)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recebido", "Recebido"),
                            ("processado", "Processado"),
                            ("ignorado", "Ignorado"),
                            ("erro", "Erro"),
                        ],
                        default="recebido",
                        max_length=24,
                    ),
                ),
                ("erro", models.TextField(blank=True)),
                ("recebido_em", models.DateTimeField(auto_now_add=True)),
                ("processado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "noticia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_eventos_noticia",
                        to="portal.noticiapublicada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de noticia Telegram",
                "verbose_name_plural": "Eventos de noticias Telegram",
                "ordering": ["-recebido_em"],
            },
        ),
    ]
