# Generated by Django 5.2.4 on 2026-04-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0059_emissaopassagem_comprovante_validators'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contafidelidade',
            index=models.Index(fields=['cliente', 'programa'], name='gestao_cont_cliente_a55da0_idx'),
        ),
        migrations.AddIndex(
            model_name='contafidelidade',
            index=models.Index(fields=['conta_administrada', 'programa'], name='gestao_cont_conta_a_31a4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='contafidelidade',
            index=models.Index(fields=['programa'], name='gestao_cont_program_286f36_idx'),
        ),
        migrations.AddIndex(
            model_name='emissaopassagem',
            index=models.Index(fields=['cliente', 'criado_em'], name='gestao_emis_cliente_1a971a_idx'),
        ),
        migrations.AddIndex(
            model_name='emissaopassagem',
            index=models.Index(fields=['conta_administrada', 'criado_em'], name='gestao_emis_conta_a_981fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='emissaopassagem',
            index=models.Index(fields=['programa', 'criado_em'], name='gestao_emis_program_2ab4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='emissaopassagem',
            index=models.Index(fields=['emissor_parceiro'], name='gestao_emis_emissor_d1f5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='emissaopassagem',
            index=models.Index(fields=['criado_em'], name='gestao_emis_criado__cd349c_idx'),
        ),
    ]
