# Generated by Django 5.2.4 on 2026-04-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0063_add_aeroporto_vvi'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissaopassagem',
            name='duracao_voo_ida_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissaopassagem',
            name='duracao_voo_volta_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissaopassagem',
            name='fuso_horario_ida',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissaopassagem',
            name='fuso_horario_volta',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
