# Generated by Django 5.2.4 on 2026-04-16 20:08

import django.db.models.deletion
import gestao.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0072_empresa_cnpj_empresa_documento_titular_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usocpf',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='documento_titular',
            field=models.CharField(blank=True, help_text='CPF para PF ou CNPJ para PJ', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='origem',
            field=models.CharField(choices=[('manual', 'Cadastro manual'), ('onboarding', 'Auto-cadastro')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Fisica'), ('PJ', 'Pessoa Juridica')], default='PJ', max_length=2),
        ),
        migrations.AddField(
            model_name='passageiro',
            name='cpf_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='passageirofrequente',
            name='cpf_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='usocpf',
            name='cpf_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=gestao.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contafidelidade',
            name='login_programa',
            field=gestao.fields.EncryptedCharField(blank=True, help_text='Login do titular junto ao programa', max_length=500),
        ),
        migrations.AlterField(
            model_name='contafidelidade',
            name='senha_programa',
            field=gestao.fields.EncryptedCharField(blank=True, help_text='Senha do titular junto ao programa', max_length=500),
        ),
        migrations.AlterField(
            model_name='documentoplataforma',
            name='tipo',
            field=models.CharField(choices=[('platform_terms', 'Termos da Plataforma'), ('platform_privacy', 'Privacidade da Plataforma'), ('platform_dpa', 'DPA / Aditivo de Tratamento de Dados'), ('platform_security', 'Politica de Seguranca / Uso Aceitavel'), ('contrato_saas', 'Contrato SaaS B2B')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='cpf',
            field=gestao.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='passaporte',
            field=gestao.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='rg',
            field=gestao.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='passageirofrequente',
            name='cpf',
            field=gestao.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='passageirofrequente',
            name='passaporte',
            field=gestao.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='passageirofrequente',
            name='rg',
            field=gestao.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='usocpf',
            name='cpf',
            field=gestao.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='usocpf',
            unique_together={('conta_fidelidade', 'cpf_hash')},
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_origem', models.CharField(choices=[('novo_pedido', 'Novo pedido'), ('cotacao_enviada', 'Cotacao enviada'), ('aprovada', 'Aprovada'), ('em_emissao', 'Em emissao'), ('emitida', 'Emitida'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('lead', 'Lead (legacy)'), ('aceita', 'Aceita (legacy)'), ('concluida', 'Concluida (legacy)')], max_length=20)),
                ('stage_destino', models.CharField(choices=[('novo_pedido', 'Novo pedido'), ('cotacao_enviada', 'Cotacao enviada'), ('aprovada', 'Aprovada'), ('em_emissao', 'Em emissao'), ('emitida', 'Emitida'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('lead', 'Lead (legacy)'), ('aceita', 'Aceita (legacy)'), ('concluida', 'Concluida (legacy)')], max_length=20)),
                ('moved_via', models.CharField(blank=True, choices=[('drag', 'Drag and drop'), ('button', 'Botao / bottom-sheet'), ('system', 'Sistema')], default='button', max_length=16)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cotacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_stage', to='gestao.cotacaovoo')),
                ('emissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_stage', to='gestao.emissaopassagem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['stage_destino', 'criado_em'], name='gestao_stag_stage_d_e6ba8a_idx')],
            },
        ),
    ]
