# Generated by Django 5.2.4 on 2026-04-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0074_empresa_endereco_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceitedocumentoplataforma',
            name='hash_documento',
            field=models.CharField(blank=True, help_text='SHA-256 do conteudo do documento no momento do aceite', max_length=64),
        ),
        migrations.AddField(
            model_name='documentoplataforma',
            name='conteudo',
            field=models.TextField(blank=True, help_text='Texto integral do documento em HTML'),
        ),
        migrations.AddField(
            model_name='documentoplataforma',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
