# Generated by Django 5.2.4 on 2026-04-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0075_documento_titulo_conteudo_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf_hash',
        ),
        migrations.RemoveField(
            model_name='passageiro',
            name='cpf_hash',
        ),
        migrations.RemoveField(
            model_name='passageirofrequente',
            name='cpf_hash',
        ),
        migrations.AlterUniqueTogether(
            name='usocpf',
            unique_together={('conta_fidelidade', 'cpf')},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='contafidelidade',
            name='login_programa',
            field=models.CharField(blank=True, help_text='Login do titular junto ao programa', max_length=150),
        ),
        migrations.AlterField(
            model_name='contafidelidade',
            name='senha_programa',
            field=models.CharField(blank=True, help_text='Senha do titular junto ao programa', max_length=150),
        ),
        migrations.AlterField(
            model_name='documentoplataforma',
            name='tipo',
            field=models.CharField(choices=[('platform_terms', 'Termos da Plataforma'), ('platform_privacy', 'Privacidade da Plataforma'), ('platform_dpa', 'DPA / Aditivo de Tratamento de Dados'), ('platform_security', 'Politica de Seguranca / Uso Aceitavel')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='passaporte',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='rg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='passageirofrequente',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='passageirofrequente',
            name='passaporte',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='passageirofrequente',
            name='rg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usocpf',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.DeleteModel(
            name='StageTransition',
        ),
        migrations.RemoveField(
            model_name='usocpf',
            name='cpf_hash',
        ),
    ]
