# Generated by Django 5.2.4 on 2026-04-17 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0076_remove_cliente_cpf_hash_remove_passageiro_cpf_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='passageiro',
            name='cpf_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='passageirofrequente',
            name='cpf_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='usocpf',
            name='cpf_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_origem', models.CharField(choices=[('novo_pedido', 'Novo pedido'), ('cotacao_enviada', 'Cotacao enviada'), ('aprovada', 'Aprovada'), ('em_emissao', 'Em emissao'), ('emitida', 'Emitida'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('lead', 'Lead (legacy)'), ('aceita', 'Aceita (legacy)'), ('concluida', 'Concluida (legacy)')], max_length=20)),
                ('stage_destino', models.CharField(choices=[('novo_pedido', 'Novo pedido'), ('cotacao_enviada', 'Cotacao enviada'), ('aprovada', 'Aprovada'), ('em_emissao', 'Em emissao'), ('emitida', 'Emitida'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('lead', 'Lead (legacy)'), ('aceita', 'Aceita (legacy)'), ('concluida', 'Concluida (legacy)')], max_length=20)),
                ('moved_via', models.CharField(blank=True, choices=[('drag', 'Drag and drop'), ('button', 'Botao / bottom-sheet'), ('system', 'Sistema')], default='button', max_length=16)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cotacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_stage', to='gestao.cotacaovoo')),
                ('emissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_stage', to='gestao.emissaopassagem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['stage_destino', 'criado_em'], name='gestao_stag_stage_d_e6ba8a_idx')],
            },
        ),
    ]
