# Generated by Django 5.2.4 on 2026-04-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0077_cliente_cpf_hash_passageiro_cpf_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacaovoo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada'), ('emissao', 'Emissão')], default='pendente', max_length=20),
        ),
    ]
