# Generated by Django 5.2.4 on 2026-04-17 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0078_pipeline_status_enviada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emissaohotel',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emissaohotel',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoteis_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emissaohotel',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('cotado', 'Cotado'), ('confirmado', 'Confirmado'), ('checkin', 'Check-in'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], db_index=True, default='solicitado', max_length=20),
        ),
        migrations.AddField(
            model_name='emissaohotel',
            name='voo_vinculado',
            field=models.ForeignKey(blank=True, help_text='Cotação/voo associado a esta reserva de hotel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoteis_vinculados', to='gestao.cotacaovoo'),
        ),
        migrations.AddField(
            model_name='stagetransition',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_stage', to='gestao.emissaohotel'),
        ),
        migrations.AlterField(
            model_name='stagetransition',
            name='stage_destino',
            field=models.CharField(choices=[('novo_pedido', 'Novo pedido'), ('cotacao_enviada', 'Cotacao enviada'), ('aprovada', 'Aprovada'), ('em_emissao', 'Em emissao'), ('emitida', 'Emitida'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('solicitado', 'Solicitado'), ('cotado', 'Cotado'), ('confirmado', 'Confirmado'), ('checkin', 'Check-in'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('lead', 'Lead (legacy)'), ('aceita', 'Aceita (legacy)'), ('concluida', 'Concluida (legacy)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stagetransition',
            name='stage_origem',
            field=models.CharField(choices=[('novo_pedido', 'Novo pedido'), ('cotacao_enviada', 'Cotacao enviada'), ('aprovada', 'Aprovada'), ('em_emissao', 'Em emissao'), ('emitida', 'Emitida'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('solicitado', 'Solicitado'), ('cotado', 'Cotado'), ('confirmado', 'Confirmado'), ('checkin', 'Check-in'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('lead', 'Lead (legacy)'), ('aceita', 'Aceita (legacy)'), ('concluida', 'Concluida (legacy)')], max_length=20),
        ),
    ]
