# Generated by Django 5.2.4 on 2026-04-17 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0079_hotel_pipeline_voo_vinculado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeira', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('elo', 'Elo'), ('amex', 'American Express'), ('hipercard', 'Hipercard'), ('diners', 'Diners Club'), ('discover', 'Discover'), ('outro', 'Outro')], max_length=20)),
                ('categoria', models.CharField(choices=[('standard', 'Standard'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('black', 'Black'), ('infinite', 'Infinite'), ('signature', 'Signature'), ('nanquim', 'Nanquim'), ('ultravioleta', 'Ultravioleta'), ('the_one', 'The One'), ('centurion', 'Centurion'), ('outro', 'Outro')], max_length=20)),
                ('banco', models.CharField(max_length=100)),
                ('num_acessos_titular', models.PositiveIntegerField(default=0, help_text='Numero de acessos a sala VIP para o titular.', verbose_name='Acessos titular')),
                ('num_acessos_convidados', models.PositiveIntegerField(default=0, help_text='Numero de acessos a sala VIP para convidados.', verbose_name='Acessos convidados')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='gestao.cliente')),
                ('passageiro_frequente', models.ForeignKey(blank=True, help_text='Se o cartao pertence a um passageiro frequente do cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes', to='gestao.passageirofrequente')),
            ],
            options={
                'verbose_name': 'Cartao do Cliente',
                'verbose_name_plural': 'Cartoes dos Clientes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaSalaVip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Dragon Pass, LoungeKey, Priority Pass, Plaza Premium', max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_sala_vip', to='gestao.cartaocliente')),
            ],
            options={
                'verbose_name': 'Programa de Sala VIP',
                'verbose_name_plural': 'Programas de Sala VIP',
                'ordering': ['nome'],
            },
        ),
        migrations.AddIndex(
            model_name='cartaocliente',
            index=models.Index(fields=['cliente'], name='gestao_cart_cliente_fb5ea7_idx'),
        ),
    ]
