# Generated by Django 5.2.4 on 2026-04-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0080_cartao_cliente_programa_sala_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaocliente',
            name='num_acessos_convidados',
        ),
        migrations.RemoveField(
            model_name='cartaocliente',
            name='num_acessos_titular',
        ),
        migrations.AddField(
            model_name='programasalavip',
            name='acessos_convidados',
            field=models.IntegerField(default=0, help_text='Numero de acessos para convidados. -1 = ilimitado.'),
        ),
        migrations.AddField(
            model_name='programasalavip',
            name='acessos_titular',
            field=models.IntegerField(default=0, help_text='Numero de acessos para o titular. -1 = ilimitado.'),
        ),
    ]
