# Generated by Django 5.2.4 on 2026-04-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0083_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageiro',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='passageiro',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='emissaopassagem',
            name='valor_referencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='emissaopassagem',
            name='valor_taxas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
