# Generated by Django 5.2.4 on 2026-04-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0084_passageiro_email_passageiro_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='programas_concierge',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('passageiro_direto', 'Passageiro direto'), ('concierge', 'Concierge'), ('conta_administrada', 'Conta administrada'), ('intermediario', 'Intermediario')], db_index=True, default='passageiro_direto', max_length=20),
        ),
        migrations.AddField(
            model_name='emissaopassagem',
            name='tipo_operacao',
            field=models.CharField(choices=[('venda_direta', 'Venda direta (Modelo 1)'), ('intermediario', 'Intermediario (Modelo 2)'), ('concierge', 'Concierge (Modelo 3)'), ('emissor_parceiro', 'Emissor parceiro (Modelo 1)')], db_index=True, default='venda_direta', max_length=20),
        ),
    ]
