# Generated by Django 5.2.4 on 2026-04-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0086_reclassificar_tipo_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissorparceiro',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='emissorparceiro',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emissorparceiro',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emissorparceiro',
            name='site',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
