# Generated by Django 5.2.4 on 2026-04-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0090_atualizacao_em_massa_e_rotulo_codigo_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='passaporte',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='passaporte_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rg',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
